<?
require_once($NPLIB_PATH."NPLib_Object.php");
require_once($NPLIB_PATH."NPLib_Sql_2.php");
require_once($NPLIB_PATH."NPLib_Net.php");
require_once($NPLIB_PATH."NPLib_String.php");
require_once($NPLIB_PATH."NPLib_System.php");
require_once($NPLIB_PATH."NPLib_PHP4_Compatible.php");
require_once($NPLIB_PATH."NPLogger.class.php");
?>